
name: Package Application with Pyinstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            

    - name: Package Application with Pyinstaller
      if: github.event_name == 'workflow_dispatch'
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: osc_midi
        path: src/dist
