
name: Package Application with Pyinstaller

on:
  push:
      tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
            

    - name: Package Application with Pyinstaller
      if: github.event_name == 'workflow_dispatch'
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: OSCMidi
        path: src/dist/windows
