
name: Package Application with Pyinstaller

on:
  push:
      tags:
      - '*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags'
        required: true
        type: string

jobs:
  build:
    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
            

    - name: Package Application with Pyinstaller
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: OSCMidi
        path: src/dist/windows
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "./"
        if: github.event_name == 'workflow_dispatch'
        tag: ${{ github.event.inputs.tags }}
